DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS article;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS post (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS article (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  img TEXT,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS comment (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  article_id INTEGER NOT NULL,
  created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES "user" (id),
  FOREIGN KEY (article_id) REFERENCES article (id)
);
